openapi: "3.0.0"
info:
  version: 1.0.0
  title: Customers
  description: Traefik Airlines Customer API
  contact:
    name: Traefik Airlines Support
    url: 'https://traefik.io/'
  license:
    name: Apache 2.0
    url: 'https://spdx.org/licenses/Apache-2.0.html'
servers:
  - url: https://api.traefik.localhost
paths:
  /organization-services/org/{orgId}:
    get:
      summary: Info for a specific customer
      operationId: showCustomerById
      tags:
        - customers
      parameters:
        - name: orgId
          in: path
          required: true
          description: The id of the customer
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid reques
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
   
components:
  schemas:
    Customer:
      type: object
      required:
        - id
        - firstName
        - lastName
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        points:
          type: integer
          format: int64
        status:
          type: string
    Customers:
      type: array
      maxItems: 100
      items:
        $ref: "#/components/schemas/Customer"
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
